version: '3.8'

networks:
  jobinder-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  elasticsearch_data:
    driver: local

services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db-jobinder
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - jobinder-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d jobinder_identity_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-jobinder
    ports:
      - "${RABBITMQ_HOST_PORT}:5672"
      - "${RABBITMQ_ADMIN_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - jobinder-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service-jobinder
    ports:
      - "${AUTH_SERVER_PORT}:8080"
    networks:
      - jobinder-net
    depends_on:
      - identity-service
    environment:
      # JWT and API Configuration
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration-ms=${JWT_EXPIRATION}
      - service.api-key.value=${API_SERVICE_SECRET}

      # Feign Client configuration to communicate with Identity Service
      - identity-service.url=${IDENTITY_SERVICE_URL_INTERNAL}

      # Prometheus Metrics Configuration
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,prometheus
      - MANAGEMENT_METRICS_TAGS_APPLICATION=auth-service

      - SERVER_PORT=8080

  identity-service:
    build:
      context: ./identity-service
    container_name: identity-service-jobinder
    ports:
      - "${IDENTITY_SERVER_PORT}:8081"
    networks:
      - jobinder-net
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      # JWT and API Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION}
      - SERVICE_API_KEY_VALUE=${API_SERVICE_SECRET}

      # Database Configuration 
      - SPRING_DATASOURCE_URL=${IDENTITY_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=update

      # Prometheus Metrics Configuration
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,prometheus
      - MANAGEMENT_METRICS_TAGS_APPLICATION=identity-service

      - SERVER_PORT=8081

  matching-service:
    build:
      context: ./matching-service
    container_name: matching-service-jobinder
    ports:
      - "${MATCHING_SERVER_PORT}:8082"
    networks:
      - jobinder-net
    depends_on:
      postgres-db:
        condition: service_healthy
      identity-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      # JWT and API Configuration 
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration-ms=${JWT_EXPIRATION}
      - service.api-key.value=${API_SERVICE_SECRET}

      # Database Configuration
      - SPRING_DATASOURCE_URL=${MATCHING_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=update

      # RabbitMQ Configuration
      - spring.rabbitmq.host=${RABBITMQ_HOST}
      - rabbitmq.queues.match-created=${RABBITMQ_QUEUES_MATCH_CREATED}

      # Feign Client configuration to communicate with Identity Service 
      - identity-service.url=${IDENTITY_SERVICE_URL_INTERNAL}

      # Prometheus Metrics Configuration
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,prometheus
      - MANAGEMENT_METRICS_TAGS_APPLICATION=matching-service

      - SERVER_PORT=8082

  chat-service:
    build:
      context: ./chat-service
    container_name: chat-service-jobinder
    ports:
      - "${CHAT_SERVER_PORT}:8083"
    networks:
      - jobinder-net
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      identity-service:
        condition: service_started
    environment:
      # Security Configuration 
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration-ms=${JWT_EXPIRATION}
      - service.api-key.value=${API_SERVICE_SECRET}

      # Database Configuration 
      - SPRING_DATASOURCE_URL=${CHAT_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - spring.jpa.hibernate.ddl-auto=update

      # RabbitMQ Configuration
      - rabbitmq.queues.match-created=${RABBITMQ_QUEUES_MATCH_CREATED}
      - spring.rabbitmq.host=${RABBITMQ_HOST}

      # Prometheus Metrics Configuration
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,prometheus
      - MANAGEMENT_METRICS_TAGS_APPLICATION=chat-service

      - SERVER_PORT=8083
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-jobinder
    ports:
      - "${PROMETHEUS_SERVER_PORT}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jobinder-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch-jobinder
    ports:
      - "${ELASTICSEARCH_SERVER_PORT}:9200"
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limit Java heap size
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - jobinder-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-jobinder
    ports:
      - "${GF_SERVER_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - jobinder-net
    depends_on:
      - elasticsearch
      - prometheus
