global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds

scrape_configs:
  - job_name: 'jobinder-microservices'
    metrics_path: '/actuator/prometheus' 
    static_configs:
      - targets: ['auth-service:8080', 'identity-service:8081', 'matching-service:8082', 'chat-service:8083']
        labels:
          application: 'Jobinder App'