global:
  scrape_interval: 30s  
  scrape_timeout: 10s   

scrape_configs:
  - job_name: 'jobinder-microservices'
    scrape_interval: 1m  
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080', 'identity-service:8081', 'matching-service:8082', 'chat-service:8083']
        labels:
          application: 'Jobinder App'